### ISSUE TITLE
Missing device in Product Database (Manufacturer Id: 0x86, Device Type: 0x3, Device ID: 0x62 ) 

### ISSUE THREAD

**Issue by rezethon** [cdjackson/HABmin#248]
Hello
I have a Aeon Labs ZW098-C55 LED Bulb that is missing from the database. Could you please add it to the database?
I believe this xml has the correct data: http://www.pepper1.net/zwavedb/device/723/723-0086-0003-0062-03-04-05-01-02.xml
My current xml:

```xml
<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>MULTILEVEL_SWITCH</genericDeviceClass>
    <specificDeviceClass>POWER_SWITCH_MULTILEVEL</specificDeviceClass>
  </deviceClass>
  <homeId>0xc11510d7</homeId>
  <nodeId>6</nodeId>
  <version>4</version>
  <manufacturer>0x86</manufacturer>
  <deviceId>0x62</deviceId>
  <deviceType>0x3</deviceType>
  <listening>true</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <supportedCommandClasses>
    <entry>
      <commandClass>SWITCH_MULTILEVEL</commandClass>
      <multiLevelSwitchCommandClass>
        <version>2</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </multiLevelSwitchCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
    <entry>
      <commandClass>ASSOCIATION</commandClass>
      <associationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configAssociations>
          <entry>
            <int>1</int>
            <associationGroup>
              <Index>1</Index>
              <Nodes/>
            </associationGroup>
          </entry>
          <entry>
            <int>2</int>
            <associationGroup>
              <Index>2</Index>
              <Nodes/>
            </associationGroup>
          </entry>
        </configAssociations>
        <maxGroups>2</maxGroups>
      </associationCommandClass>
    </entry>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_SLAVE_ENHANCED</libraryType>
        <protocolVersion>4.5</protocolVersion>
        <applicationVersion>1.4</applicationVersion>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>SCENE_ACTIVATION</commandClass>
      <sceneActivationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </sceneActivationCommandClass>
    </entry>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>CONFIGURATION</commandClass>
      <configurationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configParameters/>
      </configurationCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors>
    <int>1</int>
    <int>4</int>
  </nodeNeighbors>
  <lastSent>2015-07-18 16:00:00.414 UTC</lastSent>
  <lastReceived>2015-07-18 16:00:00.450 UTC</lastReceived>
  <applicationUpdateReceived>true</applicationUpdateReceived>
</node>
```

**Comment by cdjackson** [comment]
Added - this should be in tomorrows snapshot off cloudbees

**Comment by rezethon** [comment]
Thanks Chris
Any progress on COLOR command class? At at the moment I can only turn bulb on and off and dimm it. Is there any way of sending raw data to the device in similar way as here:
http://www.vesternet.com/resources/application-notes/apnt-91
```
Red

The LUA required to control the Red colour channel is as follows:

luup.call_action('urn:micasaverde-com:serviceId:ZWaveNetwork1','SendData',{Node='56',Data='51 5 2 2 0'},1)


    56 = Z-Wave Device ID
    51 = Color Control Command Class (0x33)
    5 = Color Set Command
    2 = Size of following data
    2 = Red colour channel
    0 = OFF (0%) - 255 = ON (100%)

```

**Comment by cdjackson** [comment]
> On 18 Jul 2015, at 19:20, rezethon <notifications@github.com> wrote:
> 
> Any progress on COLOR command class? 

Not really - it is mostly implemented, but I was unable to test (well, I did some testing with a Fibaro RGBW controller - until it died!!). I probably won’t complete this in OH1 - it will go into OH2 as it will be easier (I think) to handle the conversion from OH types into zwave types (which is going to be a problem in OH1)… I’ve just about got the OH2 binding running and will look to add this in the coming weeks (hopefully).

**Comment by rezethon** [comment]
Chris

Are you sure you correclt commited the change?
The code from https://github.com/cdjackson/openhab/commit/ea559c92e7ac7831b174411a188bd5b0f428e351 zw098.xml refers to siren:
```
+<?xml version="1.0" encoding="utf-8"?>
+<Product>
+	<Model>Smart Strip</Model>
+	<Label lang="en">Siren</Label>
+	<CommandClasses>
+		<Class>
+			<id>0x20</id>
+		</Class>
+		<Class>
+			<id>0x31</id>
+		</Class>
+		<Class>
+			<id>0x32</id>
+			<endpoint>5</endpoint>
+			<add>true</add>
+		</Class>
+		<Class>
+			<id>0x32</id>
+			<endpoint>6</endpoint>
+			<add>true</add>
+		</Class>
+		<Class>
+			<id>0x60</id>
+		</Class>
+		<Class>
+			<id>0x70</id>
+		</Class>
+		<Class>
+			<id>0x72</id>
+		</Class>
+		<Class>
+			<id>0x80</id>
+		</Class>
+		<Class>
+			<id>0x84</id>
+		</Class>
+		<Class>
+			<id>0x85</id>
+		</Class>
+		<Class>
+			<id>0x86</id>
+		</Class>
+	</CommandClasses>
+	<Associations>
+		<Group>
+			<Index>1</Index>
+			<Maximum>5</Maximum>
+			<Label lang="en">Group 1</Label>
+			<SetToController>true</SetToController>
+		</Group>
+		<Group>
+			<Index>2</Index>
+			<Maximum>5</Maximum>
+			<Label lang="en">Group 2</Label>
+			<SetToController>true</SetToController>
+		</Group>
+	</Associations>
+</Product>
```

**Comment by rezethon** [comment]
Thanks for the answer Chris
I also found some code for SmartThings that might give you some idea about color class implementation:
https://community.smartthings.com/t/color-switch-z-wave-command-class/19300

**Comment by cdjackson** [comment]
Good point :)

I used the siren file as a template and forgot to change the name, but the name in this file isn’t used - only the name in the products file is used so it won’t make any difference…

**Comment by cdjackson** [comment]
> On 19 Jul 2015, at 18:46, rezethon <notifications@github.com> wrote:
> 
> I also found some code for SmartThings that might give you some idea about color class implementation:

Thanks - the color class is already implemented - the problem is testing it and doing the translation classes to convert to the openhab data types. From what I could tell when I implemented it, the channels are different for different bulbs - the Fibaro RGBW seemed to have issues when I was testing it, but I somehow killed it so I have nothing left to test it with...

**Comment by rezethon** [comment]
Thanks Chris
That xml looks wrong as command classes are incorrect and meter class shows twice :)
And it misses color command class to 0x33.
As for your last comment this was the reason I asked you if there is any way of sending custom frames without using converters it would be great for debugging or if certain class is not yet implemented in OH.
Unless I'm completely wrong about how it works :)

**Comment by cdjackson** [comment]
> That xml looks wrong as command classes are incorrect and meter class shows twice :)
> And it misses color command class to 0x33.
> 
The command classes defined in the XML aren’t generally used - except in a couple of cases. Adding the color class here won’t make any difference. In OH2 this is removed from the file completely, so I didn’t spend too much time to get this correct. The thing that really matters is the groups and config parameters.


> As for your last comment this was the reason I asked you if there is any way of sending custom frames without using converters it would be great for debugging or if certain class is not yet implemented in OH.
> 
Unfortunately it’s not that simple - but I do agree it would be useful. I’ll have a think if there’s any way to implement something, but don’t hold your breath just yet...

**Comment by rezethon** [comment]
>The command classes defined in the XML aren’t generally used - except in a couple of cases. Adding the color class here won’t make any difference. In OH2 this is removed from the file completely, so I didn’t spend too much time to get this correct. The thing that really matters is the groups and config parameters.

That's fine. I guess I'm a bit pedantic :) I'll leave this issue open for now as pepper xml is still missing all the parameters. 

>Unfortunately it’s not that simple - but I do agree it would be useful. I’ll have a think if there’s any way to implement something, but don’t hold your breath just yet...

Perfect. I won't. But fingers crossed :)
Thanks for all your help.

**Comment by cdjackson** [comment]
> 
> That's fine. I guess I'm a bit pedantic :) I'll leave this issue open for now as pepper xml is still missing all the parameters.
> 
> 
> 
Normally I’m a stickler for adding everything ‘properly’ but just now I’m pushing forward with getting the OH2 binding running as OH1 is slowly on the out…

IF you find the parameters (say in a manual) add the link and I’ll take a look...

**Comment by rezethon** [comment]
You can find all parameters in this manual:
http://products.z-wavealliance.org/MarketCertification/File?folder=&filename=MarketCertificationFiles/1380/Aeon%20Labs%20LED%20Bulb%20manual%202.pdf

**Comment by ekfriis** [comment]
Hello,

On my (USA) bulb the device type is reported as 0x103 (instead of 0x3), so it isn't picked up. From the manual linked above, it seems the MSB of the type is is different by country:

Parameter Value (hex)
Manufacturer ID 1 0x01
Manufacturer ID 2 0x6A
Product Type ID 1 EU=0x00, US=0x01, AU=0x02
Product Type ID 2 0x03
Product ID 1 0x00
Product ID 2 0x62

I have three questions:
  1) [This](https://github.com/openhab/openhab/commits/master/bundles/binding/org.openhab.binding.zwave/database/aeon/zw098.xml) is the appropriate place to edit the xml file to test this fixes it (then build openhab from head, then copy zwave jar to my addons?)
  2) In the file above, why is the model "Smart Strip"?
  3) How do you parameterize things like this (i.e. is there something more clever multiple copies of the device for different countries?)

Thanks for all your work on openHAB and friends, it is awesome!

**Comment by cdjackson** [comment]
1) No
2) IT's probably a mistake - I've not looked but the names in these files is not used
3) We don't parameterise it- we add each type/id separately. Each device can have multiple sets of IDs to account for exactly this issue.

If you want to add a new reference, then this needs to go into the products.xml file, not the XML file for the device itself.

**Comment by cdjackson** [comment]
Hi. We now have an online database editor - it would be really appreciated if you could take a look at this to see if you can add this device. The entry should be reasonably straight forward (although I can say that as I wrote it! :) ).

The information is here -: http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide

You will need to register and email me to get edit access, but if you can have a look at this it would really be appreciated - any questions, please let me know.

**Comment by cdjackson** [comment]
Very old ZWave issue - update database if not resolved.
