### ISSUE TITLE
please add aeotec 6 in 1 multisensor to library

### ISSUE THREAD

**Issue by rm65453** [cdjackson/HABmin#274]
Hi Chris,

Here is the manual: https://www.intin.no/wp-content/uploads/2015/09/aeotec-z-wave-6-in-1-multisensor6-manual.pdf

Also once the library has been updated by you, do I just have to replace the zwave binding jar with the new one from cloudbees?

Thanks

**Comment by rm65453** [comment]
here is the pepper 1 database entry: http://www.pepper1.net/zwavedb/device/741/741-0086-0002-0064-03-04-05-01-04.xml

**Comment by cdjackson** [comment]
It is already in the database.

**Comment by rm65453** [comment]
thanks for the reply chris. This is what i see.

http://www.tiikoni.com/tis/view/?id=503b5e2

**Comment by cdjackson** [comment]
I think you must be using an old binding then as this has been in the binding for quite a while.  What version are you running?

**Comment by rm65453** [comment]
1.7.1 when i switched to the new version, all of my current nodes disappeared including the new one that was just added (the evolve fixture switch) so i reverted back to this version.

**Comment by cdjackson** [comment]
There’s no reason that nodes should disappear when you change versions. The nodes are stored in the controller. In any case, you need to use the new version and there is very very little difference between 1.7.1 and 1.8.0.

**Comment by rm65453** [comment]
so i download the addon zip file from https://openhab.ci.cloudbees.com/job/openHAB/, unzipped, deleted the 1.7.1 version file and replaced it with the new 1.8.0 version. restart openhab. the aeon sensor is showing up fine but not the evolve switch. when i repeated the same process after you added the lfm-20 with the nightly version all the nodes disappeared.

**Comment by cdjackson** [comment]
What do you mean the nodes “disappeared”? I don’t know how nodes can disappear so I don’t know what this means.

**Comment by rm65453** [comment]
ok i am gonna use the binding file from build 1041 and post a screenshot.

**Comment by rm65453** [comment]
so this time the nodes did not disappears but the lfm-20 switch which you added to the list a few days ago is still showing up as it was before the information was added to product database.

please see screenshot: http://www.tiikoni.com/tis/view/?id=c377d0d

**Comment by cdjackson** [comment]
For some reason this device is no longer in the database which is strange as it is on my computer, but not on Github. I’ll need to add it again it seems…

**Comment by rm65453** [comment]
Thanks Chris. Sorry to keep bothering you. I am gonna try to figure out how to add new products to at least the 1pepper database so i can reduce some of your workload. 

once again thanks for the prompt response.

**Comment by cdjackson** [comment]
I added the wrong number in for the LFM20 - 5426 instead of 5246…  It’s fixed now…

**Comment by rm65453** [comment]
thanks chris. am i good to download the file from cloudbees now or should i wait?

**Comment by cdjackson** [comment]
No - you need to wait until tomorrow - it normally happens in the early hours of the morning European time…

**Comment by rm65453** [comment]
Thanks Chris

**Comment by rm65453** [comment]
I updated with the latest build 1042 but the data is still not there. I will wait for build 1043 and update again.
